### ISSUE TITLE
Current LWRP is not idempotent 

### ISSUE THREAD

**Issue by thenoid** [mmmorris1975/yumgroup#1]
Current LWRP is not idempotent.  Every run it executes the yum group commands without consulting with yum for the current status of the group.

**Comment by mmmorris1975** [comment]
This is now released as version 0.5.0.  There was a minor issue uncovered with the idempotency checks on Fedora, but I was able to get that resolved so this should work on RHEL-ish and Fedora systems.  Thanks a bunch for taking the time to code this up!
